name: Package Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Dependencies
        run: npm install

      - name: Compile Extension
        run: npm run vscode:prepublish --if-present

      - name: Package VSIX
        run: npx @vscode/vsce package --no-dependencies

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension-vsix
          path: "*.vsix"
          if-no-files-found: error
